name: "Rails: run tests and linters"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint_test:
    runs-on: ubuntu-latest-m
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432:5432
    steps:
      - name: Configure dpkg
        run: |
          sudo mkdir -p /etc/dpkg/dpkg.cfg.d
          sudo sh -c 'echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/dpkg-katalyst-ci'
          sudo sh -c 'echo "path-exclude /usr/share/man/*" >> /etc/dpkg/dpkg.cfg.d/dpkg-katalyst-ci'
          sudo sh -c 'echo "path-exclude /usr/share/doc/*" >> /etc/dpkg/dpkg.cfg.d/dpkg-katalyst-ci'
          sudo sh -c 'echo "path-exclude /usr/share/doc-base/*" >> /etc/dpkg/dpkg.cfg.d/dpkg-katalyst-ci'
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          DEPENDENCIES: "libvips"
        run: sudo apt-get install --no-install-recommends -y $DEPENDENCIES || (sudo apt-get update && sudo apt-get install --no-install-recommends -y $DEPENDENCIES)
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install
      - name: Run tests
        id: test
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost/test
        run: |
          bundle exec rake
      - name: Archive screenshots and logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-output
          path: |
            log
            tmp/capybara
